import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',

    {
      'Getting Started': ['getting-started/installation', 'getting-started/quickstart'],
    },

    {
      '@forgewisp/core': [
        'core/index',
        'core/configuration',
        'core/streaming',
        'core/reasoning',
        'core/audit',
        'core/risk-tiers',
        'core/subagents',
        // Generated by `pnpm gen:api:core` → docs/core/api/*.md
        { type: 'autogenerated', dirName: 'core/api' },
      ],
    },

    {
      '@forgewisp/bundled-tools': [
        'bundled-tools/index',
        // Generated by `pnpm gen:api:bundled-tools` → docs/bundled-tools/api/*.md
        { type: 'autogenerated', dirName: 'bundled-tools/api' },
      ],
    },

    {
      '@forgewisp/mcp': [
        'mcp/index',
        'mcp/oauth',
        // Generated by `pnpm gen:api:mcp` → docs/mcp/api/*.md
        { type: 'autogenerated', dirName: 'mcp/api' },
      ],
    },
  ],
};

export default sidebars;
